from dataclasses import dataclass


@dataclass
class TaskErrorType:

    ALLOCATION_LOST: str = "ALLOCATION_LOST"
    RESOURCE_REQUEST_FAILED: str = "RESOURCE_REQUEST_FAILED"

    TIMED_OUT: str = "TIMED_OUT"
    UNABLE_START_PROCESS: str = "UNABLE_START_PROCESS"
    PROCESS_NON_ZERO_EXIT: str = "PROCESS_NON_ZERO_EXIT"
    DATA_CLIENT_DISABLED: str = "DATA_CLIENT_DISABLED"
    UNKNOWN_ERROR: str = "UNKNOWN_ERROR"
    OUTPUT_NOT_FOUND: str = "OUTPUT_NOT_FOUND"
    INPUT_NOT_FOUND: str = "INPUT_NOT_FOUND"
    TRANSITION_REFUSED: str = "TRANSITION_REFUSED"
    UNABLE_WRITE_TASK_DATA: str = "UNABLE_WRITE_TASK_DATA"
    OBJECT_STORE_TRANSFER_FAILED: str = "OBJECT_STORE_TRANSFER_FAILED"


    pass
