#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/.."

source env_configure
step docker_configure
step git_configure

step ci/steps/validate_artifact_versions
step ci/steps/build
step ci/steps/deploy

step docker_build yellowdog-sdk-python-docs \
  -f yellowdog-sdk-python-docs/Dockerfile
step docker_deploy yellowdog-sdk-python-docs

step manifest_add_docker yellowdog-sdk-python-docs
step infra_notify documentation
